### ISSUE TITLE
fixed effects gif pulling towards 0

### ISSUE THREAD

**Issue by caimiao0714** [NickCH-K/causalgraphs#1]
Hi Nick,

In the fixed effects model gif your R code generated, Xs and Ys are pulling towards 0, but in real life cases, what we normally do is set a reference for Z, and then the other groups are pulled towards this reference group, instead of 0. 

If you could set a random seed number, that would make your graphs more reproducible.

I made a more readable html generated by Rmarkdown, you may be interested in reading it on [my forked repository](https://github.com/caimiao0714/causalgraphs/blob/master/A_notebook_of_animated_causal_graphs.html). You can download the html and view it.

Thanks,
Miao

**Comment by NickCH-K** [comment]
The pull to 0 is one standard approach to fixed effects, specifically the within-estimator formulation where each variable has its individual-specific mean subtracted from it. I like the within-estimator version of FE for the graph because it's a clear application of "remove all between-Individual differences" that doesn't require any further explanation.

Adding seeds, and switching the descriptive HTML (currently at nickchk.com/causalgraphs.html) to markdown are good ideas, I'll add them to my to-do.

**Comment by caimiao0714** [comment]
Thanks Nick for explaining the within-estimator. I understand your point about the within-estimator. More generally in applied statistics, people use dummy variables for categorical variables, we call that "fixed-effects", while we name random effects for those variables that are generated from another distribution and have their hyper-parameters, but that appears to be different from what you mean here.

**Comment by NickCH-K** [comment]
The within-estimator is equivalent to the version using dummy variables (at least in terms of the coefficients on the regressors in the model), it's just a different way of calculating the estimator. You're right that the intuition for the within-estimator doesn't generalize so well to random effects, which is a downside.
